on: [push, pull_request]

name: CI
jobs:
  test:
    name: Integration
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04] # For python3.6
        python-version:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: v1-pip-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('requirements-*.txt') }}
          restore-keys: |
            v1-pip-${{ runner.os }}-${{ matrix.python-version }}
            v1-pip-${{ runner.os }}
            v1-pip-
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install mreg-cli
        run: |
          pip install -r requirements.txt
          pip install -e .
      - name: Test and compare api calls
        run: ci/run_testsuite_and_record.sh

  tox:
    name: tox
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt
      - name: Test with tox
        run: tox r
        